name: Run Laravel Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # 🟢 Create a MySQL service container
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -plaravel"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, fileinfo, bcmath, intl, pdo_mysql
          coverage: none

      - name: Copy .env
        run: cp .env.example .env

      # 🟢 Configure .env for MySQL service
      - name: Update .env for MySQL
        run: |
          sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
          sed -i 's/^DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/^DB_PORT=.*/DB_PORT=3306/' .env
          sed -i 's/^DB_DATABASE=.*/DB_DATABASE=testing/' .env
          sed -i 's/^DB_USERNAME=.*/DB_USERNAME=laravel/' .env
          sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=laravel/' .env

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Generate app key
        run: php artisan key:generate

      - name: Setup Node.js (for Breeze Vite)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install NPM packages
        run: npm ci

      - name: Build frontend assets
        run: npm run build

      # 🟡 Wait for MySQL container to be healthy before migrations
      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..10}; do
            if mysql -h 127.0.0.1 -ularavel -plaravel -e "SELECT 1" &> /dev/null; then
              echo "MySQL is ready!"
              break
            fi
            echo "MySQL not ready yet... ($i)"
            sleep 5
          done

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --without-tty
